version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: openmnd_postgres
    environment:
      POSTGRES_DB: openmnd_research
      POSTGRES_USER: openmnd_user
      POSTGRES_PASSWORD: openmnd_password
    ports:
      - "5432:5432"
    volumes:
      - openmnd_postgres_data:/var/lib/postgresql/data
    networks:
      - openmnd_network
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: openmnd_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - openmnd_es_data:/usr/share/elasticsearch/data
    networks:
      - openmnd_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: openmnd_redis
    ports:
      - "6379:6379"
    volumes:
      - openmnd_redis_data:/data
    networks:
      - openmnd_network
    restart: unless-stopped

networks:
  openmnd_network:
    driver: bridge

volumes:
  openmnd_postgres_data:
  openmnd_redis_data:
  openmnd_es_data:
